name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  folder: "PR-${{github.event.pull_request.number}}"
jobs:
  precheck:
    name: Job Info
    runs-on: windows-2019
    steps:
      - name: Run Info
        shell: cmd
        run: if "${{env.folder}}"=="PR-" (echo MAIN) else (echo ${{env.folder}})

